version: '3.1'

services:

  cactus-service:
    build: ./
    restart: always
    ports:
      - 4467:8080
    depends_on:
      - mongodb
    networks:
      - cactus-net
    volumes:
      - .:/usr/src/app

  mongodb:
    container_name: mongodb
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: AA6bm58Bi
    networks:
      - cactus-net

  mongo-express:
    container_name: mongo-express
    image: mongo-express
    restart: always
    ports:
      - 4468:8081
    environment:
      ME_CONFIG_MONGODB_SERVER: mongodb
      ME_CONFIG_MONGODB_PORT: 27017
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: AA6bm58Bi
    networks:
      - cactus-net

networks:
  cactus-net:
    driver: bridge
