version: '3.1'

services:

  mongodb:
    container_name: mongodb
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: AA6bm58Bi

  mongo-express:
    container_name: mongo-express
    image: mongo-express
    restart: always
    ports:
      - 4468:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: AA6bm58Bi
    links:
      - mongodb
    depends_on:
      - mongodb

  cactus-service:
    build: ./
    restart: always
    ports:
      - 4467:8080
    links:
      - mongodb
    depends_on:
      - mongodb
